service: s3-access-point

provider:
  name: aws
  runtime: nodejs16.x

resources:
  Resources:

    # --------------------------------------
    # ----------VCP Configuration-----------
    # --------------------------------------
    EC2VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 172.31.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        InstanceTenancy: default

    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref EC2VPC

    PrivateSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref EC2VPC
        CidrBlock: 172.31.0.0/20
        MapPublicIpOnLaunch: true

    RouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref PrivateSubnet

    S3GatewayEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        VpcId: !Ref EC2VPC
        VpcEndpointType: Gateway
        ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
        RouteTableIds:
          - !Ref RouteTable
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${S3Bucket}/*'
                - !Join  [ '', [ !GetAtt S3AccessPoint.Arn, '/object/*' ] ]
            - Effect: Allow
              Principal: '*'
              Action:
                - 's3:ListBucket'
              Resource:
                - !Sub 'arn:aws:s3:::${S3Bucket}'
                - !GetAtt S3AccessPoint.Arn

    AllowSHHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SG for SSH access
        VpcId: !Ref EC2VPC
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            FromPort: 22
            ToPort: 22
            IpProtocol: tcp

    AllowHTTPSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SG for HTTPS access
        VpcId: !Ref EC2VPC
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            FromPort: 443
            ToPort: 443
            IpProtocol: tcp

    # --------------------------------------
    # ----------EC2 Configuration-----------
    # --------------------------------------

    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-00c6177f250e07ec1
        InstanceType: t2.micro
        UserData: !Base64 ${file(ec2-user-data.sh)}
        KeyName: "EC2 Tutorial"
        IamInstanceProfile: !Ref InstanceProfile
        SubnetId: !Ref PrivateSubnet
        SecurityGroupIds:
          - !Ref AllowSHHSecurityGroup
          - !Ref AllowHTTPSSecurityGroup # Allows S3 connections
        Tags:
          - Key: Name
            Value: EC2 Instance

    InstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        InstanceProfileName: ec2-instance-profile
        Roles:
          - !Ref EC2InstanceRole

    EC2InstanceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: basic-instance-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: EC2InstancePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 's3:*'
                  Resource: '*'

    EC2InstanceConnectEndpoint:
      Type: AWS::EC2::InstanceConnectEndpoint
      Properties:
        ClientToken: 'EC2-S3-ACCESS-POINT'
        PreserveClientIp: true
        SubnetId: !Ref PrivateSubnet
    # --------------------------------------
    # -----------S3 Configuration-----------
    # --------------------------------------

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 's3-access-point-bucket-b'
      DeletionPolicy: Delete
      UpdateReplacePolicy: Retain

    MainS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: '*'
              Effect: Allow
              Resource:
                - !Sub 'arn:aws:s3:::${S3Bucket}/*'
                - !Sub 'arn:aws:s3:::${S3Bucket}'
              Principal:
                AWS: '*'
              Condition:
                StringEquals:
                  's3:DataAccessPointAccount': !Sub '${AWS::AccountId}'

    S3AccessPoint:
      Type: AWS::S3::AccessPoint
      Properties:
        Bucket: !Ref S3Bucket
        Name: main-access-point
        VpcConfiguration:
          VpcId:
            Ref: EC2VPC
        Policy:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 's3:GetObject'
                - 's3:PutObject'
              Effect: Allow
              Resource:
                - !Sub 'arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/main-access-point/object/main/*'
              Principal: '*'
            - Action:
                - 's3:ListBucket'
              Effect: Allow
              Resource:
                - !Sub 'arn:${AWS::Partition}:s3:${AWS::Region}:${AWS::AccountId}:accesspoint/main-access-point'
              Principal: '*'
