service: rds-fundamentals

provider:
  name: aws
  runtime: nodejs16.x

resources:
  Resources:
    # ---------------------------------------
    # -----------VPC Configuration-----------
    # ---------------------------------------

    RDSVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: Database VPC

    VPCInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: Database VPC IG

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref RDSVPC
        InternetGatewayId: !Ref VPCInternetGateway

    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref RDSVPC
        Tags:
          - Key: Name
            Value: Database Route Table

    DefaultIpv4Route:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId: !Ref RouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref VPCInternetGateway

    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref RDSVPC
        CidrBlock: 10.0.1.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: !Select
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
        Tags:
          - Key: Name
            Value: Public Subnet 1

    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref RDSVPC
        CidrBlock: 10.0.2.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: !Select
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
        Tags:
          - Key: Name
            Value: Public Subnet 2

    RouteTableAssociation1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref PublicSubnet1

    RouteTableAssociation2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref PublicSubnet2

    DatabaseSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Database SG for public access
        VpcId: !Ref RDSVPC
        SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            FromPort: 3306
            ToPort: 3306
            IpProtocol: tcp

    # ---------------------------------------
    # -----------RDS Configuration-----------
    # ---------------------------------------

    RDSInstance:
      Type: AWS::RDS::DBInstance
      DependsOn: VPCInternetGateway
      Properties:
        DBInstanceIdentifier: 'database-1'
        Engine: mysql
        EngineVersion: '8.0.34'
        MasterUsername: admin
        MasterUserPassword: 12345678
        DBInstanceClass: 'db.t2.micro'
        StorageType: gp2
        AllocatedStorage: 20
        MaxAllocatedStorage: 1000
        VPCSecurityGroups:
          - !Ref DatabaseSecurityGroup
        DBName: mydb
        BackupRetentionPeriod: 7
        AutoMinorVersionUpgrade: true
        DeletionProtection: true
        DBSubnetGroupName: !Ref DatabaseSubnetGroup
        Port: 3306
        PubliclyAccessible: true


    DatabaseSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: 'Subnet for MySQL database'
        DBSubnetGroupName: 'db-subnet-group'
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
        Tags:
          - Key: Name
            Value: Database Subnet Group
