service: s3-advanced

provider:
  name: aws
  runtime: nodejs16.x

custom:
  bucketName: 's3-advanced-bucket'

resources:
  Resources:
  # --------------------------------------
  # -----------S3 Configuration-----------
  # --------------------------------------
    S3Bucket:
      Type: AWS::S3::Bucket
      DependsOn:
        - S3NotificationsQueue
        - ReceiveS3MessagesPolicy
      Properties:
        BucketName: '${self:custom.bucketName}'
        NotificationConfiguration:
          QueueConfigurations:
            - Event: 's3:ObjectCreated:*'
              Queue: !GetAtt S3NotificationsQueue.Arn
        LifecycleConfiguration:
          Rules:
            - Id: DemoRule
              Status: Enabled
              ExpirationInDays: 700
              Transitions:
                - TransitionInDays: 30
                  StorageClass: STANDARD_IA
                - TransitionInDays: 60
                  StorageClass: INTELLIGENT_TIERING
                - TransitionInDays: 90
                  StorageClass: GLACIER_IR
                - TransitionInDays: 180
                  StorageClass: GLACIER
                - TransitionInDays: 365
                  StorageClass: DEEP_ARCHIVE
              NoncurrentVersionTransitions:
                - TransitionInDays: 90
                  StorageClass: GLACIER
              NoncurrentVersionExpiration:
                NoncurrentDays: 700
      DeletionPolicy: Delete
      UpdateReplacePolicy: Retain

  # --------------------------------------
  # -----------SQS Configuration----------
  # --------------------------------------
    S3NotificationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: 's3-notifications-queue'

    ReceiveS3MessagesPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Action:
                - 'SQS:SendMessage'
              Effect: Allow
              Resource: !GetAtt S3NotificationsQueue.Arn
              Principal:
                Service:
                  - 's3.amazonaws.com'
              Condition:
                ArnLike:
                  'aws:SourceArn':
                    - 'arn:aws:s3:::${self:custom.bucketName}'
        Queues:
          - !Ref S3NotificationsQueue

